/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.oopsmails.backend.libexplorer.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum AccountType implements org.apache.avro.generic.GenericEnumSymbol<AccountType> {
  SAVING, CHECKING  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AccountType\",\"namespace\":\"com.oopsmails.backend.libexplorer.avro.model\",\"symbols\":[\"SAVING\",\"CHECKING\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
