version: '3.1'

services:
  wiremock:
    image: rodolpheche/wiremock
    ports:
      - "7070:7070"
    command: --port 7070
      - -verbose
      - -global-response-templating
    volumes:
      - ./stubs:/home/wiremock
